var profile = {
  "login": "sallykingston",
  "id": 5340860,
  "avatar_url": "https://avatars.githubusercontent.com/u/5340860?v=3",
  "gravatar_id": "",
  "url": "https://api.github.com/users/sallykingston",
  "html_url": "https://github.com/sallykingston",
  "followers_url": "https://api.github.com/users/sallykingston/followers",
  "following_url": "https://api.github.com/users/sallykingston/following{/other_user}",
  "gists_url": "https://api.github.com/users/sallykingston/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/sallykingston/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/sallykingston/subscriptions",
  "organizations_url": "https://api.github.com/users/sallykingston/orgs",
  "repos_url": "https://api.github.com/users/sallykingston/repos",
  "events_url": "https://api.github.com/users/sallykingston/events{/privacy}",
  "received_events_url": "https://api.github.com/users/sallykingston/received_events",
  "type": "User",
  "site_admin": false,
  "name": "Sally Kingston",
  "company": "The Iron Yard Academy",
  "blog": "http://sallykingston.me/",
  "location": "United States",
  "email": "sally.a.kingston@gmail.com",
  "hireable": true,
  "bio": null,
  "public_repos": 16,
  "public_gists": 1,
  "followers": 7,
  "following": 0,
  "created_at": "2013-08-29T17:35:32Z",
  "updated_at": "2015-10-20T16:07:22Z"
}
